#!/bin/bash
# Setup an isolated Factorio server for factorioctl runtime tests.
#
# This script deliberately uses a test save, test RCON port, and test
# write-data directory. It must not touch the normal buddy save.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

SAVE_NAME="${SAVE_NAME:-test_map}"
RCON_PORT="${RCON_PORT:-27016}"
RCON_PASSWORD="${RCON_PASSWORD:-test_password}"
GAME_PORT="${GAME_PORT:-34198}"
SERVER_DATA_DIR="${SERVER_DATA_DIR:-$PROJECT_ROOT/.factorio-test-data}"
CONFIG_FILE="$SERVER_DATA_DIR/config.ini"
MOD_SRC="$PROJECT_ROOT/mod/claude-interface"
MOD_DST="$SERVER_DATA_DIR/mods/claude-interface"

if [ -n "${1:-}" ]; then
    SAVE_PATH="$1"
else
    SAVE_PATH="${SAVE_PATH:-$PROJECT_ROOT/saves/${SAVE_NAME}.zip}"
fi

if [[ "$SAVE_PATH" != /* ]]; then
    SAVE_PATH="$PROJECT_ROOT/$SAVE_PATH"
fi

find_factorio_bin() {
    if [ -n "${FACTORIO_BIN:-}" ]; then
        echo "$FACTORIO_BIN"
    elif [ -n "${FACTORIO_BINARY:-}" ]; then
        echo "$FACTORIO_BINARY"
    elif command -v factorio >/dev/null 2>&1; then
        command -v factorio
    elif [ -x "/mnt/games/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio" ]; then
        echo "/mnt/games/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio"
    elif [ -x "$HOME/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio" ]; then
        echo "$HOME/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio"
    elif [ -x "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio" ]; then
        echo "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio"
    elif [ -x "$HOME/Library/Application Support/Steam/steamapps/common/Factorio/factorio.app/Contents/MacOS/factorio" ]; then
        echo "$HOME/Library/Application Support/Steam/steamapps/common/Factorio/factorio.app/Contents/MacOS/factorio"
    else
        return 1
    fi
}

FACTORIO_BIN="$(find_factorio_bin)" || {
    echo "ERROR: Factorio binary not found. Set FACTORIO_BIN=/path/to/factorio"
    exit 1
}

FACTORIO_DATA="$(dirname "$(dirname "$(dirname "$FACTORIO_BIN")")")/data"
if [ ! -d "$FACTORIO_DATA" ]; then
    echo "ERROR: Could not infer Factorio data directory from $FACTORIO_BIN"
    echo "       Expected: $FACTORIO_DATA"
    exit 1
fi

echo "=== factorioctl isolated runtime setup ==="
echo "  Factorio: $FACTORIO_BIN"
echo "  Save: $SAVE_PATH"
echo "  RCON: localhost:$RCON_PORT"
echo "  Game: localhost:$GAME_PORT"
echo "  Data: $SERVER_DATA_DIR"
echo ""

echo "Building factorioctl release binaries..."
cargo build --release --quiet

mkdir -p "$PROJECT_ROOT/saves" "$PROJECT_ROOT/logs" "$SERVER_DATA_DIR"

cat > "$CONFIG_FILE" << EOF
; Auto-generated by tests/setup.sh - do not edit by hand
[path]
read-data=$FACTORIO_DATA
write-data=$SERVER_DATA_DIR

[other]
check-updates=false
EOF

rm -rf "$SERVER_DATA_DIR/mods"
mkdir -p "$SERVER_DATA_DIR/mods"
cp -R "$MOD_SRC" "$MOD_DST"
rm -rf "$SERVER_DATA_DIR/script-output/claude-chat"

if pgrep -f "factorio.*--rcon-(port|bind)[^ ]*.*$RCON_PORT" >/dev/null; then
    echo "ERROR: test server already running on RCON port $RCON_PORT"
    echo "       Stop it with: ./tests/cleanup.sh"
    exit 1
fi

if [ ! -f "$SAVE_PATH" ]; then
    echo "Creating isolated test save..."
    "$FACTORIO_BIN" \
        --config "$CONFIG_FILE" \
        --create "$SAVE_PATH" \
        --map-gen-settings "$PROJECT_ROOT/configs/test-map-gen.json"
fi

echo "Starting isolated headless server..."
LOG_FILE="$PROJECT_ROOT/logs/test-server.log"
STDIN_FIFO="$PROJECT_ROOT/logs/test-server.stdin"
STDIN_KEEPER_PID_FILE="$PROJECT_ROOT/logs/test-server.stdin.pid"
rm -f "$STDIN_FIFO" "$STDIN_KEEPER_PID_FILE"
mkfifo "$STDIN_FIFO"
nohup tail -f /dev/null > "$STDIN_FIFO" 2>/dev/null &
STDIN_KEEPER_PID=$!
echo "$STDIN_KEEPER_PID" > "$STDIN_KEEPER_PID_FILE"

setsid "$FACTORIO_BIN" \
    --config "$CONFIG_FILE" \
    --start-server "$SAVE_PATH" \
    --rcon-bind "127.0.0.1:$RCON_PORT" \
    --rcon-password "$RCON_PASSWORD" \
    --port "$GAME_PORT" \
    --server-settings "$PROJECT_ROOT/configs/test-server.json" \
    < "$STDIN_FIFO" \
    > "$LOG_FILE" 2>&1 &

SERVER_PID=$!
echo "$SERVER_PID" > "$PROJECT_ROOT/logs/test-server.pid"

echo "Server starting (PID: $SERVER_PID)"
echo "Log file: $LOG_FILE"
echo -n "Waiting for RCON..."
for _ in $(seq 1 30); do
    if ./target/release/factorioctl --port "$RCON_PORT" --password "$RCON_PASSWORD" get tick >/dev/null 2>&1; then
        echo ""
        echo "Server ready."
        exit 0
    fi
    sleep 1
    echo -n "."
done

echo ""
echo "ERROR: Server did not become ready. Check $LOG_FILE"
kill "$SERVER_PID" "$STDIN_KEEPER_PID" 2>/dev/null || true
rm -f "$STDIN_FIFO" "$STDIN_KEEPER_PID_FILE" "$PROJECT_ROOT/logs/test-server.pid"
exit 1
