#[derive(Clone, Copy, Debug)]
pub struct FactorioToolMetadata {
    pub name: &'static str,
    pub mutating: bool,
    pub read_only: bool,
    pub dry_run_safe: bool,
}

const fn tool(
    name: &'static str,
    mutating: bool,
    read_only: bool,
    dry_run_safe: bool,
) -> FactorioToolMetadata {
    FactorioToolMetadata {
        name,
        mutating,
        read_only,
        dry_run_safe,
    }
}

pub const FACTORIO_MCP_TOOLS: &[FactorioToolMetadata] = &[
    tool("send_chat_response", true, false, false),
    tool("tool_status", true, false, false),
    tool("set_status", true, false, false),
    tool("register_agent", true, false, false),
    tool("unregister_agent", true, false, false),
    tool("ensure_surface", true, false, false),
    tool("place_character", true, false, false),
    tool("set_spectator_mode", true, false, false),
    tool("ping", false, true, false),
    tool("live_state", false, true, false),
    tool("connected_player_count", false, true, false),
    tool("production_statistics", false, true, false),
    tool("get_entities", false, true, false),
    tool("get_machine_belt_positions", false, true, false),
    tool("render_map", false, true, false),
    tool("debug_wedged_state", false, true, false),
    tool("get_resources", false, true, false),
    tool("find_nearest_resource", false, true, false),
    tool("get_character", false, true, false),
    tool("can_stand_at", false, true, false),
    tool("is_player_blocked", false, true, false),
    tool("unstuck", true, false, true),
    tool("get_inventory", false, true, false),
    tool("situation_report", false, true, false),
    tool("verify_production", false, true, false),
    tool("diagnose_factory_blockers", false, true, false),
    tool("diagnose_fuel_sustainability", false, true, false),
    tool("get_tick", false, true, false),
    tool("analyze_belt_reach", false, true, false),
    tool("analyze_belt_networks", false, true, false),
    tool("analyze_belt_gaps", false, true, false),
    tool("analyze_inserters", false, true, false),
    tool("analyze_item_flow", false, true, false),
    tool("walk_to", true, false, false),
    tool("place_entity", true, false, false),
    tool("find_entity_placements", false, true, false),
    tool("plan_entity_placement_near", false, true, false),
    tool("execute_entity_placement_near", true, false, true),
    tool("build_edge_miner", false, true, false),
    tool("execute_edge_miner", true, false, true),
    tool("build_direct_smelter", false, true, false),
    tool("execute_direct_smelter", true, false, true),
    tool("mine_at", true, false, false),
    tool("craft", true, false, false),
    tool("get_recipe", false, true, false),
    tool("get_recipes_for_item", false, true, false),
    tool("get_recipes_by_category", false, true, false),
    tool("insert_items", true, false, false),
    tool("hand_feed_furnace", true, false, false),
    tool("bootstrap_smelting_once", true, false, true),
    tool("extract_items", true, false, false),
    tool("set_recipe", true, false, false),
    tool("remove_entity", true, false, false),
    tool("rotate_entity", true, false, false),
    tool("configure_inserter", true, false, false),
    tool("route_belt", true, false, true),
    tool("build_fuel_supply", true, false, true),
    tool("repair_fuel_sustainability", true, false, true),
    tool("build_lab_feed", true, false, true),
    tool("build_assembler_feed", true, false, true),
    tool("plan_machine_output", false, true, false),
    tool("build_assembler_output", true, false, true),
    tool("plan_recipe_assembler_cell", false, true, false),
    tool("build_recipe_assembler_cell", true, false, true),
    tool("plan_automation_science", false, true, false),
    tool("build_automation_science", true, false, true),
    tool("get_belt_lane_contents", false, true, false),
    tool("detect_sushi_belts", false, true, false),
    tool("trace_belt_sources", false, true, false),
    tool("get_research_status", false, true, false),
    tool("get_available_research", false, true, false),
    tool("feed_lab_from_inventory", true, false, false),
    tool("start_research", true, false, false),
    tool("get_power_status", false, true, false),
    tool("get_power_networks", false, true, false),
    tool("find_power_issues", false, true, false),
    tool("diagnose_steam_power", false, true, false),
    tool("plan_steam_power", false, true, false),
    tool("repair_steam_power", false, true, false),
    tool("extend_power_to", false, true, false),
    tool("get_alerts", false, true, false),
    tool("execute_lua", true, false, false),
    tool("broadcast_thought", false, true, false),
    tool("create_zone", true, false, false),
    tool("list_zones", false, true, false),
    tool("get_zone", false, true, false),
    tool("update_zone", true, false, false),
    tool("delete_zone", true, false, false),
    tool("scan_resources", false, true, false),
    tool("get_protected_resources", false, true, false),
    tool("check_placement", false, true, false),
    tool("find_build_area", false, true, false),
    tool("get_blank_slate", false, true, false),
    tool("clear_area", true, false, true),
];
